---
name: Docker Build/Publish Image

on:
  workflow_dispatch:

env:
  TERM: xterm

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DOCKER_TAG: pep1/3cx
      DOCKER_TARGET_PLATFORMS: linux/arm/v7

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # https://github.com/docker/build-push-action#path-context
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ env.DOCKER_TARGET_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.DOCKER_TAG }}